### ISSUE TITLE
Please add Github tags to the project

### ISSUE THREAD

**Issue by stokito** [hujun-open/pypcpc#2]
It was quite hard to find your library. Please add  Github tags like "nat-pmp" (even if you don't support it directly most users are searchin by the tag), "nat-traversial", "pcp" and "port control protocol" to make it easier to find it. Here is foe example all topics for the https://github.com/topics/nat-pmp

Also please mention in readme that there is the  https://github.com/jaraco/nat-pmp library. Maybe you can even send them a PR with the PCP support. That would be very nice.

**Comment by hujun-open** [comment]
I am surprised someone need this  after 7 years, however I have no plan to maintain this because this protocol never got widely adopted, and also this was written in py2, which is EoL, but I don't feel like to rewrite it in py3;
I will archive this repo.
